name: module_core
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  module_commons:
    path: '../module_commons'

  module_external_dependencies:
    path: '../module_external_dependencies'

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.module_core
    iosBundleIdentifier: com.example.moduleCore
