name: module_external_dependencies
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_modular: ^5.0.3
  mobx_triple: ^1.1.3+1
  dio: ^4.0.6
  flutter_triple: ^1.2.7+4
  dartz: ^0.10.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.module_external_dependencies
    iosBundleIdentifier: com.example.moduleExternalDependencies
