name: base_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  module_external_dependencies:
    path: '../module_external_dependencies'

  module_commons:
    path: '../module_commons'

  module_auth:
    path: '../module_auth'

  module_core:
    path: '../module_core'

  module_assets:
    path: '../module_assets'

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
