name: module_commons
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  module_auth:
    path: '../module_auth'

  module_assets:
    path: '../module_assets'

  module_external_dependencies:
    path: '../module_external_dependencies'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.module_commons
    iosBundleIdentifier: com.example.moduleCommons
